# Require a specific version of Ruff to be running
required-version = "0.1.9"

line-length = 120

# Enable Pyflakes `E` and `F` codes by default.
select = ["A", "C40", "E", "F", "G010", "YTT", "I", "RUF", "PLC", "PLE", "PLR", "PLW", "UP", "W"]
# Disable some Pyflakes codes by default.
# see https://beta.ruff.rs/docs/rules/ known error code information
# E501	    line-too-long	            Line too long
# E722	    do-not-use-except	        Do not use bare except, specify exception instead
# PLC1901	compare-to-empty-string	    {} can be simplified to {} as an empty string is falsey
# PLR0911	too-many-return-statements	Too many return statements ({returns}/{max_returns})
# PLR0912	too-many-branches	        Too many branches ({branches}/{max_branches})
# PLR0913	too-many-arguments	        Too many arguments ({args}/{max_args})
# PLR0915	too-many-statements	        Too many statements ({statements}/{max_statements})
# PLR2004	magic-value-comparison	    Magic value used in comparison, consider replacing {value} with a constant variable
# PLR5501	collapsible-else-if	        Consider using elif instead of else then if to remove one indentation level
# PLW0120	useless-else-on-loop	    else clause on loop without a break statement; remove the else and de-indent all the code inside it
# PLW0603	global-statement	        Using the global statement to update {name} is discouraged
# PLW2901	redefined-loop-name	        Outer {outer_kind} variable {name} overwritten by inner {inner_kind} target
# UP032	    f-string	                Use f-string instead of format call
ignore = ["E722", "PLC1901", "PLR0911", "PLR0912", "PLR0913", "PLR0915", "PLR2004", "PLR5501", "PLW0120", "PLW0603", "PLW2901", "PLW0602", "UP032",
    "RUF012", "PLW1509"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "C40", "E", "F", "G010", "YTT", "I", "RUF", "PLC", "PLE", "PLR", "PLW", "UP", "W"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "**/tests",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.10.
target-version = "py310"

[mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[isort]
# lines_between_types=1 not found rules config
force-sort-within-sections = true
# force_alphabetical_sort_within_sections=true not found rules config
extra-standard-library = ["ConfigParser", "commands"]
