app:
  name: "MyApp"
  version: "1.0"

# web server
server:
  port: 8080

# log file
log:
  level: "INFO"
  file: "app.log"

# connect local database
database:
  host: "172.17.0.2"
  port: 3306
  user: "root"
  password: "root"

# api control
apilimit:
  limit: 100
