app:
  name: "MyApp"
  version: "1.0"

server:
  port: 8080

log:
  level: "INFO"
  file: "app.log"

database:
  user: "root"
  password: "root"
  host: "172.17.0.2"
  port: 3306

apilimit:
  limit: 100