apiVersion: v1
kind: Service
metadata:
  name: goweb-service
spec:
  type: NodePort
  selector:
    app: goweb
  ports:
  - port: 8081          # Service 暴露的端口，外部访问时使用的端口
    targetPort: 8080    # 容器内部实际的端口
    nodePort: 30080      # 在集群节点上的端口号
    protocol: TCP
