[package]
name = "eg3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvm-bindings = "0.6.0"
kvm-ioctls = "0.15.0"
vm-memory = "0.12.1"
libc = "0.2.147"